---
- name: Configure Web Server
  hosts: webservers
  become: yes

  tasks:
    - name: Update all system packages
      yum:
        name: '*'
        state: latest

    - name: Ensure Docker is installed
      yum: 
        name: docker
        state: present

    - name: Start and enable the Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add the ec2-user to 'docker' group
      user:
        name: ec2-user
        groups: docker
        append: yes
    
    # Fix to the Issue with Docker permissions not taking place on first pipeline run
    - name: Reset SSH connection to apply group changes
      meta: reset_connection

    - name: Pull the latest app image from Docker Hub
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/my-homepage:latest"
        source:  pull
      become: no

    - name: Stop and remove any existing app containers
      community.docker.docker_container:
        name: my-homepage-container
        state: absent
      become: no

    - name: Run the application container
      community.docker.docker_container:
        name: my-homepage-container
        image: "{{ dockerhub_username }}/my-homepage:latest"
        state: started
        restart_policy: always
        ports:
          - "80:5000"
      become: no
