# .github/workflows/cicd-pipeline.yml

name: Multi-Stage Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  # job 1 - Build Image
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-homepage:latest

  # job 2 - Deploy to Dev  // TODO
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Runner Public IP
        id: runner_ip
        run: echo "ip=$(curl -s ifconfig.me)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Terraform Apply (Builds Infra & Creates Inventory)
        id: apply
        working-directory: ./terraform/dev
        run: |
          terraform init
          terraform apply -auto-approve \
            -var="runner_ip=${{ steps.runner_ip.outputs.ip }}" \
            -var="ssh_public_key=${{ secrets.AWS_SSH_PUBLIC_KEY }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Ansible Playbook
        working-directory: ./ansible
        run: |

          printf -- "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > /tmp/ssh_key.pem
          chmod 600 /tmp/ssh_key.pem
          
          echo "Waiting for SSH on Bastion..."
          sleep 30
          
          PROXY_COMMAND="-o ProxyCommand='ssh -W %h:%p -q  -i /tmp/ssh_key.pem ec2-user@BASTION_IP'"
                 
          
          ansible-playbook -i inventory/dev.ini playbook.yml \
            --user ec2-user \
            --private-key /tmp/ssh_key.pem \
            --extra-vars "ansible_ssh_common_args='$PROXY_COMMAND'" \
            --extra-vars "dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }}"
          
          rm /tmp/ssh_key.pem
        env:
          BASTION_IP: ${{ steps.apply.outputs.bastion_public_ip }}
          ANSIBLE_HOST_KEY_CHECKING: False
          
  
         
